import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { ROOT, DIST } from '../scripts/lib/content.mjs';
import { TAHAI_PRESS_PROVENANCE, humansText, sourceProvenanceComment } from '../scripts/lib/provenance.mjs';

function build() {
  execFileSync(process.execPath, ['scripts/build.mjs'], { cwd: ROOT, stdio: 'pipe' });
}

function walk(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(directory, entry.name);
    return entry.isDirectory() ? walk(full) : [full];
  });
}

function htmlFiles() {
  return walk(DIST).filter((file) => file.endsWith('.html'));
}

test('repository and package identity use TAHAI Press with the required creator credit', () => {
  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  const readme = fs.readFileSync(path.join(ROOT, 'README.md'), 'utf8');
  assert.equal(pkg.name, 'tahai-press');
  assert.equal(pkg.author.name, 'Justin Tahai and TAHAI Web Services');
  assert.equal(pkg.author.url, 'https://tahai.net');
  assert.match(readme, /^# TAHAI Press/m);
  assert.match(readme, /\*\*Created by Justin Tahai and TAHAI Web Services\*\*/);
  assert.match(readme, /\[https:\/\/tahai\.net\]\(https:\/\/tahai\.net\)/);
});

test('every generated HTML page carries exact non-visible TAHAI Press provenance', () => {
  build();
  const files = htmlFiles();
  assert.ok(files.length >= 20);
  for (const file of files) {
    const html = fs.readFileSync(file, 'utf8');
    assert.equal((html.match(/<meta name="generator" content="TAHAI Press">/g) || []).length, 1, path.relative(DIST, file));
    assert.equal((html.match(/Generated by TAHAI Press/g) || []).length, 1, path.relative(DIST, file));
    assert.match(html, new RegExp(sourceProvenanceComment().replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }
});

test('template project links are explicit, and all visible project attribution disappears in publisher mode', () => {
  build();
  const templateHome = fs.readFileSync(path.join(DIST, 'index.html'), 'utf8');
  const templateBody = templateHome.match(/<body\b[^>]*>([\s\S]*?)<\/body>/i)?.[1] || '';
  assert.match(templateBody, /https:\/\/github\.com\/JTAHAI\/tahai-press/);
  assert.match(templateBody, /https:\/\/tahai\.net/);
  assert.doesNotMatch(templateHome, /<meta\s+name="keywords"/i);

  const sitePath = path.join(ROOT, 'content/site.json');
  const original = fs.readFileSync(sitePath, 'utf8');
  try {
    const publisher = JSON.parse(original);
    publisher.template_mode = false;
    publisher.title = 'Example Gazette';
    publisher.short_title = 'Example Gazette';
    publisher.tagline = 'Independent reporting for the public record.';
    publisher.logo = '';
    publisher.seo.social_profiles = [];
    fs.writeFileSync(sitePath, `${JSON.stringify(publisher, null, 2)}\n`);
    build();
    for (const file of htmlFiles()) {
      const html = fs.readFileSync(file, 'utf8');
      const body = html.match(/<body\b[^>]*>([\s\S]*?)<\/body>/i)?.[1] || '';
      assert.doesNotMatch(body, /Justin Tahai|TAHAI Web Services|https:\/\/tahai\.net|github\.com\/JTAHAI\/tahai-press|TAHAI Press demo edition/i, path.relative(DIST, file));
      assert.doesNotMatch(html, /<a\b[^>]*href="https:\/\/tahai\.net/i, path.relative(DIST, file));
      assert.doesNotMatch(html, /<meta\s+name="keywords"/i, path.relative(DIST, file));
    }
  } finally {
    fs.writeFileSync(sitePath, original);
    build();
  }
});

test('humans.txt and the well-known TAHAI Press record match the fixed provenance contract', () => {
  build();
  assert.equal(fs.readFileSync(path.join(DIST, 'humans.txt'), 'utf8'), humansText());
  assert.deepEqual(
    JSON.parse(fs.readFileSync(path.join(DIST, '.well-known/tahai-press.json'), 'utf8')),
    TAHAI_PRESS_PROVENANCE
  );
});

test('SEO and social metadata remain publisher-configured and standards-based', () => {
  const sitePath = path.join(ROOT, 'content/site.json');
  const original = fs.readFileSync(sitePath, 'utf8');
  try {
    const publisher = JSON.parse(original);
    publisher.template_mode = false;
    publisher.title = 'Example Gazette';
    publisher.short_title = 'Example Gazette';
    publisher.tagline = 'Independent reporting for the public record.';
    publisher.logo = '';
    publisher.seo.social_profiles = [];
    fs.writeFileSync(sitePath, `${JSON.stringify(publisher, null, 2)}\n`);
    build();
    const home = fs.readFileSync(path.join(DIST, 'index.html'), 'utf8');
    const article = fs.readFileSync(path.join(DIST, 'stories/sample-written-story/index.html'), 'utf8');
    for (const html of [home, article]) {
      assert.match(html, /<meta property="og:title"/);
      assert.match(html, /<meta property="og:description"/);
      assert.match(html, /<meta name="twitter:card"/);
      assert.match(html, /<script type="application\/ld\+json">/);
      assert.doesNotMatch(html, /"publisher"[^<]*tahai\.net/i);
    }
    assert.match(home, /"@type":"WebSite"/);
    assert.match(article, /"@type":"Article"/);
    assert.match(article, /article:published_time/);
  } finally {
    fs.writeFileSync(sitePath, original);
    build();
  }
});

test('sitemap and feeds expose only configured publication URLs and published entries', () => {
  build();
  const sitemap = fs.readFileSync(path.join(DIST, 'sitemap.xml'), 'utf8');
  const locs = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((match) => match[1]);
  assert.ok(locs.length >= 20);
  assert.equal(new Set(locs).size, locs.length);
  assert.equal(locs.every((loc) => loc.startsWith('https://example.pages.dev/')), true);
  assert.doesNotMatch(sitemap, /tahai\.net/i);

  const rss = fs.readFileSync(path.join(DIST, 'feed.xml'), 'utf8');
  assert.equal((rss.match(/<item>/g) || []).length, 4);
  assert.doesNotMatch(rss, /tahai\.net/i);

  const jsonFeed = JSON.parse(fs.readFileSync(path.join(DIST, 'feed.json'), 'utf8'));
  assert.equal(jsonFeed.items.length, 4);
  assert.equal(jsonFeed.home_page_url, 'https://example.pages.dev');
});
