export const TAHAI_PRESS_PROVENANCE = Object.freeze({
  software: 'TAHAI Press',
  creator: 'Justin Tahai',
  organization: 'TAHAI Web Services',
  website: 'https://tahai.net',
  license: 'Apache-2.0'
});

export function sourceProvenanceComment() {
  return `<!--\nGenerated by ${TAHAI_PRESS_PROVENANCE.software}\nCreated by ${TAHAI_PRESS_PROVENANCE.creator} and ${TAHAI_PRESS_PROVENANCE.organization}\n${TAHAI_PRESS_PROVENANCE.website}\n-->`;
}

export function humansText() {
  return [
    `Software: ${TAHAI_PRESS_PROVENANCE.software}`,
    `Creator: ${TAHAI_PRESS_PROVENANCE.creator}`,
    `Organization: ${TAHAI_PRESS_PROVENANCE.organization}`,
    `Website: ${TAHAI_PRESS_PROVENANCE.website}`,
    `License: ${TAHAI_PRESS_PROVENANCE.license}`,
    ''
  ].join('\n');
}
