export const READER_REACH_DEFAULTS = Object.freeze({
  enabled: true,
  offline_enabled: true,
  saved_articles_enabled: true,
  browser_share_enabled: true,
  current_edition_enabled: true,
  current_edition_count: 8,
  offline_article_count: 12
});

export function readerReachConfig(site = {}) {
  const input = site.reader_reach && typeof site.reader_reach === 'object' && !Array.isArray(site.reader_reach)
    ? site.reader_reach
    : {};
  const positiveInteger = (value, fallback, maximum) => {
    const number = Number(value);
    return Number.isInteger(number) && number > 0 && number <= maximum ? number : fallback;
  };
  return {
    enabled: input.enabled !== false,
    offlineEnabled: input.offline_enabled !== false,
    savedArticlesEnabled: input.saved_articles_enabled !== false,
    browserShareEnabled: input.browser_share_enabled !== false,
    currentEditionEnabled: input.current_edition_enabled !== false,
    currentEditionCount: positiveInteger(input.current_edition_count, READER_REACH_DEFAULTS.current_edition_count, 50),
    offlineArticleCount: positiveInteger(input.offline_article_count, READER_REACH_DEFAULTS.offline_article_count, 50)
  };
}

function js(value) {
  return JSON.stringify(value).replaceAll('</', '<\\/');
}

export function serviceWorkerSource({ version, precache = [], offlineRoute = '/offline/' } = {}) {
  const cacheName = `tahai-press-reader-${String(version || 'dev').replace(/[^a-z0-9.-]/gi, '-')}`;
  const normalized = [...new Set(precache.filter((item) => typeof item === 'string' && item.startsWith('/')))];
  return `/* Generated by TAHAI Press. Static offline reader; no analytics or remote API. */
const CACHE_NAME = ${js(cacheName)};
const OFFLINE_ROUTE = ${js(offlineRoute)};
const PRECACHE = ${js(normalized)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((key) => key.startsWith('tahai-press-reader-') && key !== CACHE_NAME).map((key) => caches.delete(key)))).then(() => self.clients.claim()));
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).then((response) => {
      if (response.ok) caches.open(CACHE_NAME).then((cache) => cache.put(request, response.clone()));
      return response;
    }).catch(async () => (await caches.match(request)) || (await caches.match(url.pathname)) || (await caches.match(OFFLINE_ROUTE))));
    return;
  }

  event.respondWith(caches.match(request).then((cached) => {
    const refreshed = fetch(request).then((response) => {
      if (response.ok) caches.open(CACHE_NAME).then((cache) => cache.put(request, response.clone()));
      return response;
    }).catch(() => cached);
    return cached || refreshed;
  }));
});
`;
}
